name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm test -- --watchAll=false --coverage
      env:
        REACT_APP_SENTRY_DSN: ${{ secrets.REACT_APP_SENTRY_DSN }}
      
    - name: Upload test coverage
      uses: actions/upload-artifact@v2
      if: success() || failure()
      with:
        name: coverage
        path: coverage/
        
    - name: Check test coverage
      run: |
        $coverage = Get-Content coverage/coverage-final.json | ConvertFrom-Json
        $threshold = 30
        $totalCoverage = [math]::Round($coverage.total.lines.pct, 2)
        if ($totalCoverage -lt $threshold) {
          Write-Error "Test coverage ($totalCoverage%) is below threshold ($threshold%)"
          exit 1
        }