name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Create env file
      run: |
        echo "REACT_APP_SENTRY_DSN=${{ secrets.REACT_APP_SENTRY_DSN }}" > .env
      
    - name: Run tests
      run: npm test -- --watchAll=false --coverage --passWithNoTests
      env:
        CI: true
        REACT_APP_SENTRY_DSN: ${{ secrets.REACT_APP_SENTRY_DSN }}
      
    - name: Check if coverage directory exists
      run: |
        if [ ! -d "coverage" ]; then
          echo "Coverage directory does not exist!"
          exit 1
        fi
      
    - name: Upload coverage reports
      uses: actions/upload-artifact@v3
      if: success()
      with:
        name: coverage-reports
        path: |
          coverage/
          !coverage/lcov-report/


